from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS
import time

# Configured to match docker-compose environment variables
INFLUX_URL = "http://localhost:8086"
INFLUX_TOKEN = "adminpassword"  # Replace with actual token generated by InfluxDB UI if needed
INFLUX_ORG = "research"
INFLUX_BUCKET = "transmissions"

client = InfluxDBClient(url=INFLUX_URL, token=INFLUX_TOKEN, org=INFLUX_ORG)
write_api = client.write_api(write_options=SYNCHRONOUS)

def log_transmission(frequencies: list, duration: float, status: str):
    """Records transmission metrics to the time-series ledger."""
    point = (
        Point("rf_transmission")
        .tag("status", status)
        .field("duration_seconds", float(duration))
        .field("frequency_count", len(frequencies))
    )
    
    # Add individual frequencies as distinct fields
    for idx, freq in enumerate(frequencies):
        point.field(f"freq_{idx}", float(freq))
        
    write_api.write(bucket=INFLUX_BUCKET, org=INFLUX_ORG, record=point)
